namespace: jupyter

image:
  image: jupyter/minimal-notebook
  imagePullPolicy: Always
  command: ["jupyter"]
  args:
  - "notebook"
  - "--ip=0.0.0.0"
  - "--no-browser"
  - "--port=8888"
  - "--NotebookApp.token=''"
  - "--NotebookApp.password=''"
  - "--NotebookApp.allow_origin='*'"
  - "--NotebookApp.authenticate_prometheus=False"
  - "--NotebookApp.base_url=$(NB_PREFIX)"
  - "--NotebookApp.default_url=/tree"

port: 8888
targetPort: 8888
url: /notebook/blair-drummond/jupyter
