apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    notebook-name: jupyter
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        {{ toYaml .Values.image | nindent 8 }}
        {{ if not .Values.image.env }}
        env:
        {{ end }}
        - name: NB_PREFIX
          value: {{ .Values.url }}
        ports:
        - containerPort: {{ .Values.targetPort }}
