apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  ports: 
  - name: notebook-port
    port: {{ .Values.port }}
    targetPort: {{ .Values.targetPort }}
  selector:
    app: {{ .Chart.Name }}
